version: '3.5'

services:
  api:
    stop_grace_period: 1s
    build:
      dockerfile: Dockerfile
      target: production
      context: .
    healthcheck:
#      todo right becomes unhealthy but endpoint path exist in the app 
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/health", ">", "/var/log/healthcheck.log", "||", "exit", "1" ]
      timeout: 5s
      retries: 1
    ports:
      - "8080:8080"
    depends_on: 
      - db
  db:
    image: postgres:14-alpine
    command: postgres -c 'max_connections=200'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./docker-volumes/mysql_data:/var/lib/postgresql/bbs-data
    logging:
      options:
        max-size: "5m"
        max-file: "3"